### PR TITLE
Trivial fix to trigger build

### PR DESCRIPTION
**Pull request by akaszynski**
Removes an unnecessary file to trigger the build. Seems to be failing on `release/0.1`.

### CODE REVIEW

**Comment by akaszynski** [comment]
@Louis-Pujol, running into a strange error where windows isn't simplifying. When you get a chance, would you mind looking into this? Both Linux and Mac work out, so it might have to do with some quirk with Windows (potentially int32 vs int64).

**Comment by Louis-Pujol** [comment]
Hi @akaszynski . Sorry for the delay, I completely missed the notification.

I have no clue about what's going on, I added the generation of pytest html reports to the CI pipeline. I'll try to detect the problem.

**Comment by Louis-Pujol** [comment]
Just added a workflow file that tests on ubuntu and windows and upload the reports from pytest. Every prints before failing inside tests function are reported there.

First observation : the test simplify_agg fails on windows, it does not simplify at all. However, the function simplify is working for other tests (I did some prints in test replay_sphere). Maybe it comes from the aggresivness arg. But I hardly understand how outputs are different between ubuntu and windows. I'll have a look later, does anybody have an idea of where the issue comes from ?

Ubuntu:

ubuntu


Windows:
windows

**Comment by akaszynski** [comment]
Biggest issue I've encountered between Windows and Linux when working with C has been the treatment of `int` vs. `long` as Windows and Linux treat the lengths of those int types differently. Not sure if it's an issue here, but it's best to use `size_t` or `int32_t` as much as possible.

**Comment by akaszynski** [comment]
Ran this locally on Windows with zero issues:

```
================================================= test session starts =================================================
platform win32 -- Python 3.11.3, pytest-7.4.3, pluggy-1.2.0
rootdir: C:\Users\Alex\source\fast-simplification
configfile: pytest.ini
collected 10 items

tests\test_map_isolated_points.py .                                                                              [ 10%]
tests\test_replay.py ....                                                                                        [ 50%]
tests\test_simplify.py .....                                                                                     [100%]

================================================= 10 passed in 4.40s ==================================================
PS C:\Users\Alex\source\fast-simplification>
```

Interestingly, this issue only arose when GitHub upgraded their Windows runner. I'm going to open another PR to use `windows-2019`.

**Comment by Louis-Pujol** [comment]
Update : with `windows-2019` the threshold values are exactly the same than with ubuntu. https://github.com/Louis-Pujol/fast-simplification/actions/runs/7390480735

Sounds very weird that `windows-latest` leads to different values...

**Comment by akaszynski** [comment]
We'll build with Windows-2019 and hopefully the problem will fix itself in a few years when they drop 2019. Otherwise, we'll revisit it.

**Pull request closed without merging**
