### PR TITLE
Add a replay_decimation functionnality

### PR DESCRIPTION
**Pull request by Louis-Pujol**
Hello,

Following my last week contribution, I implemented a function to replay a decimation process thanks to the history of collapses.

This functionnality is presented as a function `replay_simplification`, here is a basic example of usage : 

`
replay_points, replay_triangles, indices_mapping = replay_simplification(points, triangles, collapses)
`

`replay_points` and `replay_triangles` will be the same as the output of `simplify`, and `indice_mapping` a '(n_points, )' array of integer encoding the correspondence of vertices from the original mesh to the decimated one.

I see three applications of this function:
- Maintaining a correspondence between points of high and low-resolution meshes
- Partially replay a decimation process by giving a portion of collapses to `replay_simplification`, and eventually create a nested collection of decimated meshes
- Apply the same decimation process on another mesh with the same connectivity

Applications 1 and 2 are illustrated in examples/replay.py, 2 points are randomly picked on the mesh and thanks to indice_mapping, we are able, after replaying, to find associations on decimated meshes
ReplayDecimation

Regarding the code, I added the following files to the `fast_simplification` folder : `Replay.h`, `wrapper_replay.h`, `_replay.pyx` and `replay.py`, following the spirit of the code for `simplify`. This was a convenient solution for me because the compilation of a second cython module, independent from simplify, prevent from breaking previous code.

I've also added a test file : `test_replay.py` where I test that replaying decimation leads to the same result as applying `simplify`, both on toy examples and on Sphere and louis_louvre meshes from pyvista examples gallery.

Let me now if you think it could be added to fast-simplification.
Thanks

### CODE REVIEW

**Comment by Louis-Pujol** [comment]
I've adjusted the tolerance for this test.

**Comment by akaszynski** [comment]
Need another patch release?

**Comment by Louis-Pujol** [comment]
Yes maybe to add documentation. I've updated my fork of the repository, added a paragraph at the end of readme.rst to present replay_simplification and made modifications to the doc folder. Do I need to create a new PR or it is possible to reopen this one ?

**Comment by akaszynski** [comment]
> Do I need to create a new PR or it is possible to reopen this one ?

Please create another PR. Sorry, should have asked if you were ready to merge.

**Comment by Louis-Pujol** [comment]
No worry, I do it right now

**Pull request merged**
